# Generated by Django 6.0.2 on 2026-02-21 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("assigned_by_user_id", models.IntegerField()),
                ("due_date", models.DateTimeField()),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField(editable=False)),
                ("question_type", models.CharField(max_length=255)),
                ("points", models.IntegerField()),
                ("order_index", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("permissions", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SimulatedEmail",
            fields=[
                ("email_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=100)),
                ("sender_name", models.CharField(max_length=100)),
                ("sender_email", models.CharField(max_length=255)),
                ("body", models.TextField(editable=False)),
                ("is_phishing", models.BooleanField()),
                ("difficulty", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_users", models.IntegerField()),
                ("features_notes", models.TextField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="TestLesson",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(editable=False)),
                ("test_type", models.CharField(max_length=100)),
                ("passing_score", models.IntegerField()),
                ("estimated_minutes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("attempt_id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("passed", models.BooleanField()),
                (
                    "assignment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.assignment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="company_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.company"
            ),
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                ("choice_id", models.AutoField(primary_key=True, serialize=False)),
                ("choice_text", models.TextField(editable=False)),
                ("is_correct", models.BooleanField()),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                ("free_text_answer", models.TextField()),
                ("is_correct", models.BooleanField()),
                (
                    "attempt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.attempt"
                    ),
                ),
                (
                    "choice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.answerchoice",
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_Date", models.DateField()),
                (
                    "company_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.subscriptionplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="test_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.testlesson"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="test_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.testlesson"
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=100)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailSimulation",
            fields=[
                ("simulation_id", models.AutoField(primary_key=True, serialize=False)),
                ("sent_at", models.DateTimeField()),
                ("interacted_at", models.DateTimeField()),
                ("clicked_link", models.BooleanField()),
                ("reported_as_phishing", models.BooleanField()),
                ("outcome", models.CharField(max_length=255)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
                (
                    "email_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.simulatedemail",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
