# Generated by Django 6.0.2 on 2026-02-25 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="choice_id",
        ),
        migrations.RemoveField(
            model_name="attempt",
            name="assignment_id",
        ),
        migrations.RemoveField(
            model_name="response",
            name="attempt_id",
        ),
        migrations.RemoveField(
            model_name="emailsimulation",
            name="company_id",
        ),
        migrations.RemoveField(
            model_name="emailsimulation",
            name="email_id",
        ),
        migrations.RemoveField(
            model_name="emailsimulation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="response",
            name="question_id",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="assigned_by_user_id",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="question",
            name="order_index",
        ),
        migrations.RemoveField(
            model_name="question",
            name="points",
        ),
        migrations.AddField(
            model_name="assignment",
            name="company_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.company",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="start_date",
            # use a callable default so existing rows receive a valid datetime
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="response",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="score",
            # default zero ensures migration can populate existing rows
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("lesson_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("questions", models.TextField()),
                ("lesson_material", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(editable=False)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_taken", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="assignment",
            name="test_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.test"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.test"
            ),
        ),
        migrations.DeleteModel(
            name="AnswerChoice",
        ),
        migrations.DeleteModel(
            name="Attempt",
        ),
        migrations.DeleteModel(
            name="SimulatedEmail",
        ),
        migrations.DeleteModel(
            name="EmailSimulation",
        ),
        migrations.DeleteModel(
            name="Response",
        ),
        migrations.DeleteModel(
            name="TestLesson",
        ),
    ]
