# Generated by Django 6.0.2 on 2026-04-20 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_lesson_old_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonScore",
            fields=[
                (
                    "lesson_score_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="api.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Module",
        ),
        migrations.AddConstraint(
            model_name="lessonscore",
            constraint=models.UniqueConstraint(
                fields=("user", "lesson"), name="unique_user_lesson_score"
            ),
        ),
    ]
